(function(modules){var installedModules={};function __webpack_require__(moduleId){if(installedModules[moduleId]){return installedModules[moduleId].exports;}
var module=installedModules[moduleId]={i:moduleId,l:false,exports:{}};modules[moduleId].call(module.exports,module,module.exports,__webpack_require__);module.l=true;return module.exports;}
__webpack_require__.m=modules;__webpack_require__.c=installedModules;__webpack_require__.i=function(value){return value;};__webpack_require__.d=function(exports,name,getter){if(!__webpack_require__.o(exports,name)){Object.defineProperty(exports,name,{configurable:false,enumerable:true,get:getter});}};__webpack_require__.n=function(module){var getter=module&&module.__esModule?function getDefault(){return module['default'];}:function getModuleExports(){return module;};__webpack_require__.d(getter,'a',getter);return getter;};__webpack_require__.o=function(object,property){return Object.prototype.hasOwnProperty.call(object,property);};__webpack_require__.p="";return __webpack_require__(__webpack_require__.s=100);})
({1:(function(module,exports){module.exports={Foundation:window.Foundation};}),100:(function(module,exports,__webpack_require__){module.exports=__webpack_require__(34);}),3:(function(module,exports){module.exports={rtl:window.Foundation.rtl,GetYoDigits:window.Foundation.GetYoDigits,transitionend:window.Foundation.transitionend};}),34:(function(module,__webpack_exports__,__webpack_require__){"use strict";Object.defineProperty(__webpack_exports__,"__esModule",{value:true});var __WEBPACK_IMPORTED_MODULE_0__foundation_core__=__webpack_require__(1);var __WEBPACK_IMPORTED_MODULE_0__foundation_core___default=__webpack_require__.n(__WEBPACK_IMPORTED_MODULE_0__foundation_core__);var __WEBPACK_IMPORTED_MODULE_1__foundation_util_box__=__webpack_require__(64);__WEBPACK_IMPORTED_MODULE_0__foundation_core__["Foundation"].Box=__WEBPACK_IMPORTED_MODULE_1__foundation_util_box__["a"];}),64:(function(module,__webpack_exports__,__webpack_require__){"use strict";__webpack_require__.d(__webpack_exports__,"a",function(){return Box;});var __WEBPACK_IMPORTED_MODULE_0__foundation_util_core__=__webpack_require__(3);var __WEBPACK_IMPORTED_MODULE_0__foundation_util_core___default=__webpack_require__.n(__WEBPACK_IMPORTED_MODULE_0__foundation_util_core__);var Box={ImNotTouchingYou:ImNotTouchingYou,OverlapArea:OverlapArea,GetDimensions:GetDimensions,GetOffsets:GetOffsets,GetExplicitOffsets:GetExplicitOffsets};function ImNotTouchingYou(element,parent,lrOnly,tbOnly,ignoreBottom){return OverlapArea(element,parent,lrOnly,tbOnly,ignoreBottom)===0;};function OverlapArea(element,parent,lrOnly,tbOnly,ignoreBottom){var eleDims=GetDimensions(element),topOver,bottomOver,leftOver,rightOver;if(parent){var parDims=GetDimensions(parent);bottomOver=parDims.height+parDims.offset.top-(eleDims.offset.top+eleDims.height);topOver=eleDims.offset.top-parDims.offset.top;leftOver=eleDims.offset.left-parDims.offset.left;rightOver=parDims.width+parDims.offset.left-(eleDims.offset.left+eleDims.width);}else{bottomOver=eleDims.windowDims.height+eleDims.windowDims.offset.top-(eleDims.offset.top+eleDims.height);topOver=eleDims.offset.top-eleDims.windowDims.offset.top;leftOver=eleDims.offset.left-eleDims.windowDims.offset.left;rightOver=eleDims.windowDims.width-(eleDims.offset.left+eleDims.width);}
bottomOver=ignoreBottom?0:Math.min(bottomOver,0);topOver=Math.min(topOver,0);leftOver=Math.min(leftOver,0);rightOver=Math.min(rightOver,0);if(lrOnly){return leftOver+rightOver;}
if(tbOnly){return topOver+bottomOver;}
return Math.sqrt(topOver*topOver+bottomOver*bottomOver+leftOver*leftOver+rightOver*rightOver);}
function GetDimensions(elem){elem=elem.length?elem[0]:elem;if(elem===window||elem===document){throw new Error("I'm sorry, Dave. I'm afraid I can't do that.");}
var rect=elem.getBoundingClientRect(),parRect=elem.parentNode.getBoundingClientRect(),winRect=document.body.getBoundingClientRect(),winY=window.pageYOffset,winX=window.pageXOffset;return{width:rect.width,height:rect.height,offset:{top:rect.top+winY,left:rect.left+winX},parentDims:{width:parRect.width,height:parRect.height,offset:{top:parRect.top+winY,left:parRect.left+winX}},windowDims:{width:winRect.width,height:winRect.height,offset:{top:winY,left:winX}}};}
function GetOffsets(element,anchor,position,vOffset,hOffset,isOverflow){console.log("NOTE: GetOffsets is deprecated in favor of GetExplicitOffsets and will be removed in 6.5");switch(position){case 'top':return __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0__foundation_util_core__["rtl"])()?GetExplicitOffsets(element,anchor,'top','left',vOffset,hOffset,isOverflow):GetExplicitOffsets(element,anchor,'top','right',vOffset,hOffset,isOverflow);case 'bottom':return __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0__foundation_util_core__["rtl"])()?GetExplicitOffsets(element,anchor,'bottom','left',vOffset,hOffset,isOverflow):GetExplicitOffsets(element,anchor,'bottom','right',vOffset,hOffset,isOverflow);case 'center top':return GetExplicitOffsets(element,anchor,'top','center',vOffset,hOffset,isOverflow);case 'center bottom':return GetExplicitOffsets(element,anchor,'bottom','center',vOffset,hOffset,isOverflow);case 'center left':return GetExplicitOffsets(element,anchor,'left','center',vOffset,hOffset,isOverflow);case 'center right':return GetExplicitOffsets(element,anchor,'right','center',vOffset,hOffset,isOverflow);case 'left bottom':return GetExplicitOffsets(element,anchor,'bottom','left',vOffset,hOffset,isOverflow);case 'right bottom':return GetExplicitOffsets(element,anchor,'bottom','right',vOffset,hOffset,isOverflow);case 'center':return{left:$eleDims.windowDims.offset.left+$eleDims.windowDims.width/2-$eleDims.width/2+hOffset,top:$eleDims.windowDims.offset.top+$eleDims.windowDims.height/2-($eleDims.height/2+vOffset)};case 'reveal':return{left:($eleDims.windowDims.width-$eleDims.width)/2+hOffset,top:$eleDims.windowDims.offset.top+vOffset};case 'reveal full':return{left:$eleDims.windowDims.offset.left,top:$eleDims.windowDims.offset.top};break;default:return{left:__webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0__foundation_util_core__["rtl"])()?$anchorDims.offset.left-$eleDims.width+$anchorDims.width-hOffset:$anchorDims.offset.left+hOffset,top:$anchorDims.offset.top+$anchorDims.height+vOffset};}}
function GetExplicitOffsets(element,anchor,position,alignment,vOffset,hOffset,isOverflow){var $eleDims=GetDimensions(element),$anchorDims=anchor?GetDimensions(anchor):null;var topVal,leftVal;switch(position){case 'top':topVal=$anchorDims.offset.top-($eleDims.height+vOffset);break;case 'bottom':topVal=$anchorDims.offset.top+$anchorDims.height+vOffset;break;case 'left':leftVal=$anchorDims.offset.left-($eleDims.width+hOffset);break;case 'right':leftVal=$anchorDims.offset.left+$anchorDims.width+hOffset;break;}
switch(position){case 'top':case 'bottom':switch(alignment){case 'left':leftVal=$anchorDims.offset.left+hOffset;break;case 'right':leftVal=$anchorDims.offset.left-$eleDims.width+$anchorDims.width-hOffset;break;case 'center':leftVal=isOverflow?hOffset:$anchorDims.offset.left+$anchorDims.width/2-$eleDims.width/2+hOffset;break;}
break;case 'right':case 'left':switch(alignment){case 'bottom':topVal=$anchorDims.offset.top-vOffset+$anchorDims.height-$eleDims.height;break;case 'top':topVal=$anchorDims.offset.top+vOffset;break;case 'center':topVal=$anchorDims.offset.top+vOffset+$anchorDims.height/2-$eleDims.height/2;break;}
break;}
return{top:topVal,left:leftVal};}})});